# This file is generated by Nx.
#
# Build the docker image with `pnpm exec nx docker-build backroad-example`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t backroad-example`.
FROM node:20 as builder
WORKDIR /app
RUN corepack enable && corepack prepare pnpm@10.27.0 --activate
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc ./
RUN pnpm install --frozen-lockfile
COPY . .
RUN pnpm run build-example-app

FROM node:20 as runner
COPY --from=builder /app/dist/apps/backroad-example /app
WORKDIR /app
RUN corepack enable && corepack prepare pnpm@10.27.0 --activate

# RUN addgroup --system backroad-example && \
#     adduser --system --group backroad-example backroad-example

# RUN chown -R backroad-example:backroad-example .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN pnpm install --prod --frozen-lockfile
EXPOSE 3333
CMD [ "node", "." ]
