import {
  defaultValueFallbacks,
  type BackroadComponent,
  type BackroadContainer,
  type BackroadNode,
  type BackroadUser,
  type ComponentPropsMapping,
  type ContainerPropsMapping,
  type GenericBackroadComponent,
  type InbuiltComponentTypes,
  type InbuiltContainerTypes,
} from '@backroad/core';
import omit from 'lodash/omit';
import superjson from 'superjson';
// import {File} from "formidable"
import {
  BackroadSession,
  type DownloadDataResolver,
} from '../server/sessions/session';
import { ObjectHasher } from './object-hasher';

type BackroadComponentFormat<ComponentType extends InbuiltComponentTypes> = {
  id?: BackroadComponent<ComponentType, false>['id'];
} & BackroadComponent<ComponentType, false>['args'];

type BackroadContainerFormat<ContainerType extends InbuiltContainerTypes> =
  BackroadContainer<ContainerType, false>['args'];

/**
 * Manages the addition of nodes to the tree and also returns vaulues where applicable
 */

export class BackroadNodeManager<
  ContainerType extends InbuiltContainerTypes = 'page'
> {
  constructor(
    public container: BackroadContainer<ContainerType, false>,
    private backroadSession: BackroadSession
  ) {}

  reset(container: BackroadContainer<ContainerType, false>) {
    this.container = container;
    this.backroadSession.renderQueue.addToQueue(
      this.#getRenderPayload(container, this.backroadSession)
    );
  }
  private getAutoGeneratedId<T extends InbuiltComponentTypes>(
    props: BackroadComponentFormat<T>,
    type: T
  ) {
    const autoGeneratedIdInputs = {
      ...omit(props, ['id', 'defaultValue']),
      type,
    };
    return ObjectHasher.hash(autoGeneratedIdInputs);
  }

  #constructContainerObject<T extends InbuiltContainerTypes>(
    props: BackroadContainerFormat<T>,
    type: T
  ) {
    const nodePath = this.#getDescendantKey();
    const containerNode = {
      path: nodePath,
      args: props as unknown as ContainerPropsMapping[T]['args'],
      type: type,
    };

    return containerNode;
  }

  #addContainerDescendant<ContainerType extends InbuiltContainerTypes>(
    containerNodeData: Omit<
      BackroadContainer<ContainerType>,
      'path' | 'children'
    > & {
      children?: BackroadContainer<ContainerType, false>['children'];
    }
  ) {
    const containerNode = {
      ...containerNodeData,
      path: this.#getDescendantKey(),
      children: [],
    };
    this.container.children.push(containerNode);
    this.backroadSession.renderQueue.addToQueue(
      this.#getRenderPayload(containerNode, this.backroadSession)
    );
    return new BackroadNodeManager(
      containerNode as BackroadContainer<ContainerType>,
      this.backroadSession
    );
  }

  getOrDefault<T>(id: string, defaultValue: T) {
    this.backroadSession.setValueIfNotSet(id, defaultValue);
    return JSON.parse(JSON.stringify(this.backroadSession.valueOf(id))) as T;
  }
  setValue(id: string, value: any) {
    this.backroadSession.setValue(id, value);
  }
  // you should not have to call this manually — use
  // #initialiseAndAddComponentDescendant (for the value) or
  // #initialiseAndAddComponentNode (for the node) instead.
  #addComponentDescendant<ComponentType extends InbuiltComponentTypes>(
    nodeData: BackroadComponent<ComponentType, false>
  ) {
    const castedNodeData = nodeData as GenericBackroadComponent;
    this.container.children.push(castedNodeData);
    this.backroadSession.renderQueue.addToQueue(
      this.#getRenderPayload(castedNodeData, this.backroadSession)
    );
    return this.backroadSession.valueOf<ComponentType>(nodeData.id);
  }
  // you should not have to call this manually — use
  // #initialiseAndAddComponentDescendant (for the value) or
  // #initialiseAndAddComponentNode (for the node) instead.
  #initialiseAndConstructComponentObject<T extends InbuiltComponentTypes>(
    props: BackroadComponentFormat<T>,
    type: T
  ) {
    const nodePath = this.#getDescendantKey();
    const componentId = props.id || this.getAutoGeneratedId(props, type);
    this.backroadSession.setValueIfNotSet(
      componentId,
      'defaultValue' in props
        ? props.defaultValue
        : typeof defaultValueFallbacks[type] === 'function'
        ? defaultValueFallbacks[type]({ args: props })
        : type in defaultValueFallbacks
        ? defaultValueFallbacks[type]
        : null
    );
    const componentNode = {
      id: componentId,
      path: nodePath,
      args: omit(props, [
        'id',
        'type',
        'defaultValue',
      ]) as unknown as ComponentPropsMapping[T]['args'],
      type: type,
    };

    return componentNode;
  }
  // Construct a component, add it to the tree, and return the NODE. Most
  // callers want the value (#initialiseAndAddComponentDescendant wraps this);
  // streaming needs the node itself to re-emit it in place — see `streamable`.
  #initialiseAndAddComponentNode<T extends InbuiltComponentTypes>(
    props: BackroadComponentFormat<T>,
    type: T
  ) {
    const node = this.#initialiseAndConstructComponentObject(props, type);
    this.#addComponentDescendant(node);
    return node;
  }
  #initialiseAndAddComponentDescendant<T extends InbuiltComponentTypes>(
    props: BackroadComponentFormat<T>,
    type: T
  ) {
    const node = this.#initialiseAndAddComponentNode(props, type);
    return this.backroadSession.valueOf<T>(node.id);
  }
  #getRenderPayload(
    node: BackroadNode<false, false>,
    session: BackroadSession
  ) {
    if ('id' in node) {
      return superjson.stringify({ ...node, value: session.valueOf(node.id) });
    }
    return superjson.stringify(node);
  }
  #getDescendantKey() {
    return `${this.container.path ? this.container.path + '.' : ''}children.${
      this.container.children.length
    }`;
  }
  sidebar(props: BackroadContainerFormat<'sidebar'>) {
    return this.backroadSession.rootNodeManager.#addContainerDescendant(
      this.#constructContainerObject(props, 'sidebar')
    );
  }
  base(props: BackroadContainerFormat<'base'>) {
    return this.#addContainerDescendant(
      this.#constructContainerObject(props, 'base')
    );
  }
  // A dock: its children are pinned to the bottom of the enclosing frame (the
  // page) while the rest of the page scrolls above them. Used to keep a chat
  // input in place while message bubbles grow.
  bottom(props: BackroadContainerFormat<'bottom'> = {}) {
    return this.#addContainerDescendant(
      this.#constructContainerObject(props, 'bottom')
    );
  }
  page(props: BackroadContainerFormat<'page'>) {
    if (props.path === '/') {
      throw new Error(
        'br.page({ path: "/" }) is not allowed — the root br object already represents the home page. Add content directly to br instead.'
      );
    }
    return this.backroadSession.rootNodeManager.#addContainerDescendant(
      this.#constructContainerObject(props, 'page')
    );
  }
  columns(props: BackroadContainerFormat<'columns'>) {
    const columnsContainer = this.#addContainerDescendant(
      this.#constructContainerObject(props, 'columns')
    );
    return (
      typeof props.columns === 'number'
        ? [...Array(props.columns)]
        : props.columns
    ).map(() =>
      columnsContainer.#addContainerDescendant({ type: 'base', args: {} })
    );
  }
  collapse(props: BackroadContainerFormat<'collapse'>) {
    return this.#addContainerDescendant(
      this.#constructContainerObject(props, 'collapse')
    );
  }
  tabs(props: BackroadContainerFormat<'tabs'>) {
    const tabsContainer = this.#addContainerDescendant(
      this.#constructContainerObject(props, 'tabs')
    );
    return [...Array(props.labels.length)].map(() =>
      tabsContainer.#addContainerDescendant({ type: 'base', args: {} })
    );
  }
  chatMessage(props: BackroadContainerFormat<'chat_message'>) {
    props.loadingPromise?.then(() => {
      this.backroadSession.renderQueue.updateProps({
        loadingPromise: undefined,
      });
    });
    return this.#addContainerDescendant(
      this.#constructContainerObject(props, 'chat_message')
    );
  }

  link(props: BackroadComponentFormat<'link'>) {
    return this.#initialiseAndAddComponentDescendant(props, 'link');
  }
  linkGroup(props: BackroadComponentFormat<'link_group'>) {
    return this.#initialiseAndAddComponentDescendant(props, 'link_group');
  }
  loading(props: BackroadComponentFormat<'loading_spinner'>) {
    return this.#initialiseAndAddComponentDescendant(props, 'loading_spinner');
  }
  stats(props: BackroadComponentFormat<'stats'>) {
    return this.#initialiseAndAddComponentDescendant(props, 'stats');
  }
  multiselect(props: BackroadComponentFormat<'multiselect'>) {
    const val = this.#initialiseAndAddComponentDescendant(props, 'multiselect');

    return val;
  }
  json(props: BackroadComponentFormat<'json'>) {
    return this.#initialiseAndAddComponentDescendant(props, 'json');
  }
  title(props: BackroadComponentFormat<'title'>) {
    return this.#initialiseAndAddComponentDescendant(props, 'title');
  }

  button(props: BackroadComponentFormat<'button'>) {
    return this.#initialiseAndAddComponentDescendant(props, 'button');
  }
  downloadButton(
    props: BackroadComponentFormat<'download_button'> & {
      // File contents to serve when clicked. Always a function so the work is
      // deferred until a download is actually requested — it won't run on the
      // (common) runs where the button is never clicked. Return a string for
      // text or a Uint8Array/Buffer for binary formats; sync or async.
      data: DownloadDataResolver;
      // Name the downloaded file is saved as. Defaults to "download".
      filename?: string;
      // MIME type for the response. Inferred from the filename extension when
      // omitted, falling back to application/octet-stream.
      mime?: string;
    }
  ) {
    // Keep the payload off the tree: only `label` (in `rest`) becomes the
    // node's args, so reruns never re-ship the file. The contents are stored
    // server-side, keyed by the component id, and streamed on click from
    // GET /api/download/:sessionId/:id — filename/mime defaults are resolved
    // there.
    const { data, filename, mime, ...rest } = props;
    const node = this.#initialiseAndAddComponentNode(rest, 'download_button');
    this.backroadSession.setDownload(node.id, { data, filename, mime });
    return this.backroadSession.valueOf<'download_button'>(node.id);
  }
  numberInput(props: BackroadComponentFormat<'number_input'>) {
    return this.#initialiseAndAddComponentDescendant(props, 'number_input');
  }
  write(props: BackroadComponentFormat<'markdown'>) {
    return this.#initialiseAndAddComponentDescendant(props, 'markdown');
  }
  // A markdown node you can rewrite in place. `write()` appends a fresh child
  // on every call; this creates the node ONCE — fixing its path in the tree —
  // and hands back an `update(body)` that re-emits that same node. The client
  // merges renders by path (`set(tree, path, node)`), so each update patches
  // this one element instead of adding siblings. The Backroad analog of
  // Streamlit's `c = st.empty(); c.markdown(acc)`. Use this when the content
  // isn't a clean async iterable (interleaved reasoning, SDK callbacks, …);
  // for the common token-stream case reach for `writeStream`.
  streamable(props: Partial<BackroadComponentFormat<'markdown'>> = {}) {
    const node = this.#initialiseAndAddComponentNode(
      // `streaming: true` tells the renderer to re-render this node in place
      // rather than remounting on each body change — smooth, memoized streaming
      // (matches Streamlit). Static `write()` nodes omit it and remount on
      // change so a server-driven update can't be starved by a focused input.
      { body: '', ...props, streaming: true },
      'markdown'
    );
    return {
      update: (body: string | number) => {
        node.args = { ...node.args, body };
        this.backroadSession.renderQueue.addToQueue(
          this.#getRenderPayload(node, this.backroadSession)
        );
      },
    };
  }
  // Pumps an async iterable of text chunks into a single markdown node,
  // re-rendering the accumulated text once per chunk (full-replacement
  // streaming). Each `await` between chunks lets the render queue flush, so the
  // bubble grows live. Returns the complete string so the *caller* owns
  // persistence (e.g. appending it to a messages state) — mirrors Streamlit's
  // `st.write_stream`.
  async writeStream(
    stream: AsyncIterable<string>,
    props: Partial<BackroadComponentFormat<'markdown'>> = {}
  ): Promise<string> {
    const { update } = this.streamable(props);
    let acc = '';
    for await (const chunk of stream) {
      acc += chunk;
      update(acc);
    }
    return acc;
  }
  line(props: BackroadComponentFormat<'line_chart'>) {
    return this.#initialiseAndAddComponentDescendant(props, 'line_chart');
  }
  select(props: BackroadComponentFormat<'select'>) {
    return this.#initialiseAndAddComponentDescendant(props, 'select');
  }
  image(props: BackroadComponentFormat<'image'>) {
    return this.#initialiseAndAddComponentDescendant(props, 'image');
  }
  iframe(props: BackroadComponentFormat<'iframe'>) {
    return this.#initialiseAndAddComponentDescendant(props, 'iframe');
  }
  table(props: BackroadComponentFormat<'table'>) {
    return this.#initialiseAndAddComponentDescendant(props, 'table');
  }
  bar(props: BackroadComponentFormat<'bar_chart'>) {
    return this.#initialiseAndAddComponentDescendant(props, 'bar_chart');
  }
  pie(props: BackroadComponentFormat<'pie_chart'>) {
    return this.#initialiseAndAddComponentDescendant(props, 'pie_chart');
  }
  doughnut(props: BackroadComponentFormat<'doughnut_chart'>) {
    return this.#initialiseAndAddComponentDescendant(props, 'doughnut_chart');
  }
  radar(props: BackroadComponentFormat<'radar_chart'>) {
    return this.#initialiseAndAddComponentDescendant(props, 'radar_chart');
  }
  scatter(props: BackroadComponentFormat<'scatter_chart'>) {
    return this.#initialiseAndAddComponentDescendant(props, 'scatter_chart');
  }
  chatInput(props: BackroadComponentFormat<'chat_input'>) {
    return this.#initialiseAndAddComponentDescendant(props, 'chat_input');
  }
  colorPicker(props: BackroadComponentFormat<'color_picker'>) {
    return this.#initialiseAndAddComponentDescendant(props, 'color_picker');
  }
  checkbox(props: BackroadComponentFormat<'checkbox'>) {
    return this.#initialiseAndAddComponentDescendant(props, 'checkbox');
  }
  toggle(props: BackroadComponentFormat<'toggle'>) {
    return this.#initialiseAndAddComponentDescendant(props, 'toggle');
  }
  radio(props: BackroadComponentFormat<'radio'>) {
    return this.#initialiseAndAddComponentDescendant(props, 'radio');
  }
  textInput(props: BackroadComponentFormat<'text_input'>) {
    return this.#initialiseAndAddComponentDescendant(props, 'text_input');
  }
  textArea(props: BackroadComponentFormat<'text_area'>) {
    return this.#initialiseAndAddComponentDescendant(props, 'text_area');
  }
  slider(props: BackroadComponentFormat<'slider'>) {
    return this.#initialiseAndAddComponentDescendant(props, 'slider');
  }
  dateInput(props: BackroadComponentFormat<'date_input'>) {
    return this.#initialiseAndAddComponentDescendant(props, 'date_input');
  }
  timeInput(props: BackroadComponentFormat<'time_input'>) {
    return this.#initialiseAndAddComponentDescendant(props, 'time_input');
  }
  // A toast node renders nothing in the page flow; the client renderer fires a
  // sonner notification on mount. The microtask render queue flushes each run
  // separately, so a button's set→unset reruns give the node one real mount
  // (firing the toast) before the unset removes it.
  toast(props: BackroadComponentFormat<'toast'>) {
    return this.#initialiseAndAddComponentDescendant(props, 'toast');
  }
  fileUpload(props: BackroadComponentFormat<'file_upload'>) {
    return this.#initialiseAndAddComponentDescendant(props, 'file_upload');
  }
  video(props: BackroadComponentFormat<'video'>) {
    return this.#initialiseAndAddComponentDescendant(props, 'video');
  }

  get user(): BackroadUser {
    return this.backroadSession.user;
  }

  login(provider?: string) {
    // Social sign-in hits the better-auth API directly; plain login sends
    // the browser to the React auth page (/auth/signin), NOT the API mount
    // (/api/* is only better-auth's handler — it renders no UI).
    const url = provider
      ? `/api/auth/sign-in/social?provider=${encodeURIComponent(provider)}`
      : '/auth/signin';
    this.backroadSession.socketManager
      .getSocket(this.backroadSession.sessionId)
      .emit('auth_redirect', { url }, () => undefined);
  }

  logout() {
    // The client handler hits better-auth's sign-out endpoint to clear the
    // cookie, then navigates to /auth/signin.
    this.backroadSession.socketManager
      .getSocket(this.backroadSession.sessionId)
      .emit('auth_signout', undefined, () => undefined);
  }
}
