import { Socket } from 'socket.io';
import { IServerSocketEventHandler } from './base';

/**
 * Also join the room specified in message (which will be the session id generated by the browser socket connection)
 * @param socket
 * @returns
 */
export const handleInit: IServerSocketEventHandler =
  (socket: Socket) => (props: { sessionId: string }) => {
    console.log('received init request');
    socket.join(props.sessionId);
  };
