name: RELEASE
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: 11.5.2
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm -r --if-present run lint
      - name: Test
        run: pnpm -r --if-present run test
      - name: Release
        run: pnpm exec semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          NPM_TOKEN: ${{ secrets.BACKROAD_ORG_NPM_TOKEN }}
